name: CI
on:
  push:
    paths-ignore:
      # https://help.github.com/en/actions/reference/workflow-syntax-for-github-actions
      - "docs/**"
      - "**.md"
      - "LICENSE"
  pull_request:
    paths-ignore:
      - "docs/**"
      - "**.md"
      - "LICENSE"
jobs:
  build:
    name: Build
    runs-on: windows-latest
    strategy:
      fail-fast: false
      matrix:
        b7z_target: [b7z-win64, b7z-arm64]
        include:
          - b7z_target: b7z-win64
            arch: win64
          - b7z_target: b7z-arm64
            arch: arm64
    steps:
      - uses: lukka/get-cmake@latest
      - uses: actions/checkout@v3
        with:
          fetch-depth: 1
      - name: compile-b7z
        run: pwsh -NoProfile -NoLogo -ExecutionPolicy unrestricted -File "./build.ps1" -Target "${{ matrix.arch }}"
      - name: check_artifact_hash
        shell: pwsh
        run: |
          Set-Location build
          $item=Get-Item *.zip
          $obj=Get-FileHash -Algorithm SHA256 $item.FullName
          $baseName=Split-Path -Leaf $item.FullName
          $env:B7Z_ASSET_NAME="$baseName"
          $hashtext=$obj.Algorithm+":"+$obj.Hash.ToLower()
          Write-Host "$env:B7Z_ASSET_NAME`n$hashtext"
      - name: Upload release
        uses: svenstaro/upload-release-action@v2
        if: startsWith(github.ref, 'refs/tags/')
        with:
          file_glob: true
          file: build/b7z-*.zip
          tag: ${{ github.ref }}
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          overwrite: true
